### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by DanielZanchi** [sciv-img/Cwebp#1]
Seems nice, but how do you use it after adding the package?

**Comment by KenjiTakahashi** [comment]
You probably shouldn't, AFAIK using C module "shims" as separate packages is deprecated (though I am still using it fine).
Anyway, you can have a look at https://github.com/sciv-img/sciv/blob/master/Package.swift and https://github.com/sciv-img/sciv/blob/ac5ea9f48c2b94a4ad345eb6ec78087b864b0450/Sources/Imager.swift#L9 for example usage.
Don't think there will ever be any docs here, sorry.
